spring:
  jpa:
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:db
---
spring:
  config:
    activate:
      on-profile: dev
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
        web-admin-password: dbadmin
  jpa:
    show-sql: true
logging:
  level:
    com.example.manager: DEBUG
